"""Add conditions table

Revision ID: 0bc10a4b1267
Revises: f2df042d83bc
Create Date: 2026-05-06 23:20:26.123456

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bc10a4b1267'
down_revision: Union[str, None] = 'f2df042d83bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.String(length=40), nullable=False),
    sa.Column('duration_remaining', sa.Integer(), nullable=False),
    sa.Column('persistence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'character_id', 'condition_type', name='uq_campaign_character_condition')
    )
    op.create_index(op.f('ix_conditions_campaign_id_character_id'), 'conditions', ['campaign_id', 'character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conditions_campaign_id_character_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
