"""add stall counter to campaign

Revision ID: 2e8197e3fdef
Revises: 0bc10a4b1267
Create Date: 2026-05-12 00:19:53.227724

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e8197e3fdef'
down_revision: Union[str, None] = '0bc10a4b1267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('stall_counter', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_npc_portraits_npc_id'), 'npc_portraits', ['npc_id'], unique=False)
    op.create_index(op.f('ix_npc_portraits_campaign_id'), 'npc_portraits', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conditions_campaign_id_character_id'), 'conditions', ['campaign_id', 'character_id'], unique=False)
    op.drop_column('campaigns', 'stall_counter')
    # ### end Alembic commands ###
