"""add level and hp to npcs

Revision ID: 3b80a1983338
Revises: d3c344c0c1d4
Create Date: 2026-04-30 00:10:22.458966

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b80a1983338'
down_revision: Union[str, None] = 'd3c344c0c1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('npcs', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('npcs', sa.Column('max_hp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'max_hp')
    op.drop_column('npcs', 'current_hp')
    op.drop_column('npcs', 'level')
    # ### end Alembic commands ###
