function buildNineSliceFrame({
  id,
  label,
  baseName,
  top = "160 x 12",
  right = "12 x 160",
  bottom = "160 x 12",
  left = "12 x 160",
  corner = "24 x 24",
  center = "64 x 64 tile",
}) {
  return {
    id,
    label,
    slices: {
      topLeft: {
        name: `${baseName}-corner-tl.svg`,
        dimensions: corner,
        resize: "fixed",
      },
      top: {
        name: `${baseName}-top-bar.svg`,
        dimensions: top,
        resize: "stretch width",
      },
      topRight: {
        name: `${baseName}-corner-tr.svg`,
        dimensions: corner,
        resize: "fixed",
      },
      left: {
        name: `${baseName}-left-rail.svg`,
        dimensions: left,
        resize: "stretch height",
      },
      center: {
        name: `${baseName}-center-fill.png`,
        dimensions: center,
        resize: "tile / fill both",
      },
      right: {
        name: `${baseName}-right-rail.svg`,
        dimensions: right,
        resize: "stretch height",
      },
      bottomLeft: {
        name: `${baseName}-corner-bl.svg`,
        dimensions: corner,
        resize: "fixed",
      },
      bottom: {
        name: `${baseName}-bottom-bar.svg`,
        dimensions: bottom,
        resize: "stretch width",
      },
      bottomRight: {
        name: `${baseName}-corner-br.svg`,
        dimensions: corner,
        resize: "fixed",
      },
    },
  };
}

export const ASSET_FRAME_SPECS = {
  shell: buildNineSliceFrame({
    id: "shell",
    label: "Outer chassis shell",
    baseName: "shell-frame",
    top: "220 x 18",
    right: "18 x 220",
    bottom: "220 x 18",
    left: "18 x 220",
    corner: "28 x 28",
    center: "96 x 96 tile",
  }),
  topbar: buildNineSliceFrame({
    id: "topbar",
    label: "Topbar module",
    baseName: "topbar-frame",
    top: "180 x 14",
    right: "14 x 80",
    bottom: "180 x 14",
    left: "14 x 80",
    corner: "22 x 22",
    center: "64 x 64 tile",
  }),
  turnFeed: buildNineSliceFrame({
    id: "turnFeed",
    label: "Narrative feed frame",
    baseName: "turn-feed-frame",
    top: "130 x 10",
    right: "10 x 160",
    bottom: "130 x 10",
    left: "10 x 160",
    corner: "20 x 20",
    center: "48 x 48 tile",
  }),
  sceneScreen: buildNineSliceFrame({
    id: "sceneScreen",
    label: "Scene monitor bezel",
    baseName: "scene-screen-frame",
    top: "180 x 16",
    right: "16 x 180",
    bottom: "180 x 16",
    left: "16 x 180",
    corner: "26 x 26",
    center: "96 x 96 tile",
  }),
  utilityRail: buildNineSliceFrame({
    id: "utilityRail",
    label: "Utility icon rail",
    baseName: "utility-rail-frame",
    top: "56 x 12",
    right: "12 x 72",
    bottom: "56 x 12",
    left: "12 x 72",
    corner: "18 x 18",
    center: "24 x 24 tile",
  }),
  utilityPopout: buildNineSliceFrame({
    id: "utilityPopout",
    label: "Utility popout module",
    baseName: "utility-popout-frame",
    top: "180 x 14",
    right: "14 x 180",
    bottom: "180 x 14",
    left: "14 x 180",
    corner: "22 x 22",
    center: "48 x 48 tile",
  }),
  statusPanel: buildNineSliceFrame({
    id: "statusPanel",
    label: "Status subpanel",
    baseName: "status-panel-frame",
    top: "150 x 12",
    right: "12 x 120",
    bottom: "150 x 12",
    left: "12 x 120",
    corner: "18 x 18",
    center: "48 x 48 tile",
  }),
  presenceBar: buildNineSliceFrame({
    id: "presenceBar",
    label: "Scene presence strip",
    baseName: "presence-strip-frame",
    top: "200 x 12",
    right: "12 x 80",
    bottom: "200 x 12",
    left: "12 x 80",
    corner: "20 x 20",
    center: "64 x 32 tile",
  }),
  commandBar: buildNineSliceFrame({
    id: "commandBar",
    label: "Command relay housing",
    baseName: "command-bar-frame",
    top: "200 x 14",
    right: "14 x 72",
    bottom: "200 x 14",
    left: "14 x 72",
    corner: "22 x 22",
    center: "64 x 32 tile",
  }),
};

export function getAssetFrameSpec(frameId) {
  return ASSET_FRAME_SPECS[frameId] ?? null;
}
