export const SCENE_ART_LIBRARY = [
  {
    id: "crescent-block-barracks",
    src: "/scene-art/crescent_block_barracks.png",
    sourcePath: "output/imagegen/scene-art-candidates/crescent_block_barracks.png",
    label: "Crescent Block Barracks",
    tone: "friendly",
    scope: "campaign",
    category: "habitation",
    concept: "lowRed mining station barracks",
    keywords: ["crescent block", "crescent block barracks", "barracks", "hab block", "davan quarters", "worker barracks"],
  },
  {
    id: "lykos-station",
    src: "/scene-art/lykos_station.png",
    sourcePath: "output/imagegen/scene-art-candidates/lykos_station.png",
    label: "Lykos Station",
    tone: "friendly",
    scope: "campaign",
    category: "habitation",
    concept: "cramped lowRed station habitation",
    keywords: ["lykos station", "lykos", "cramped habitation", "graffiti", "small port", "jupiter visible"],
  },
  {
    id: "copper-admin-hub",
    src: "/scene-art/copper_admin_hub.png",
    sourcePath: "output/imagegen/scene-art-candidates/copper_admin_hub.png",
    label: "Copper Admin Hub",
    tone: "friendly",
    scope: "campaign",
    category: "bureaucratic",
    concept: "clinical bureaucratic admin office",
    keywords: ["copper admin", "copper admin hub", "bureaucratic office", "filing systems", "clerks", "clinical admin"],
  },
  {
    id: "surface-relay-tower",
    src: "/scene-art/surface_relay_tower.png",
    sourcePath: "output/imagegen/scene-art-candidates/surface_relay_tower.png",
    label: "Surface Relay Tower",
    tone: "friendly",
    scope: "campaign",
    category: "exterior",
    concept: "Ganymede exterior communication array",
    keywords: ["surface relay tower", "relay tower", "ganymede exterior", "communication array", "radiation shield", "ice plain"],
  },
  {
    id: "mars-wasteland",
    src: "/scene-art/mars_wasteland.png",
    sourcePath: "output/imagegen/scene-art-candidates/mars_wasteland.png",
    label: "Mars wasteland",
    tone: "friendly",
    scope: "generic",
    category: "exterior",
    concept: "red surface wasteland",
    keywords: ["mars wasteland", "wasteland", "desert plain", "dust storm", "surface exterior", "red horizon"],
  },
  {
    id: "maintenance-deck",
    src: "/scene-art/maintenance_deck.png",
    sourcePath: "output/imagegen/scene-art-candidates/maintenance_deck.png",
    label: "Maintenance deck",
    tone: "friendly",
    scope: "generic",
    category: "interior",
    concept: "grimy service deck",
    keywords: ["maintenance deck", "service tunnel", "conduit", "exposed piping", "fluorescent", "utility deck"],
  },
  {
    id: "the-melt",
    src: "/scene-art/the_melt.png",
    sourcePath: "output/imagegen/scene-art-candidates/the_melt.png",
    label: "The Melt",
    tone: "friendly",
    scope: "campaign",
    category: "industrial",
    concept: "molten extraction works",
    keywords: ["the melt", "melt", "molten extraction", "hellish orange glow", "industrial corridor", "panel j 14"],
  },
  {
    id: "the-gyre",
    src: "/scene-art/the_gyre.png",
    sourcePath: "output/imagegen/scene-art-candidates/the_gyre.png",
    label: "The Gyre",
    tone: "friendly",
    scope: "campaign",
    category: "market",
    concept: "underground black market",
    keywords: ["the gyre", "gyre", "underground market", "amber lighting", "black market", "market"],
  },
  {
    id: "codovan-tier",
    src: "/scene-art/codovan_tier.png",
    sourcePath: "output/imagegen/scene-art-candidates/codovan_tier.png",
    label: "The Codovan Tier",
    tone: "gold",
    scope: "campaign",
    category: "imperial",
    concept: "white marble imperial atrium",
    keywords: ["codovan tier", "white marble atrium", "jupiter through dome glass", "prefect hall", "codovan"],
  },
  {
    id: "gold-throne-room",
    src: "/scene-art/gold_throne_room.png",
    sourcePath: "assets/gold_throne_room.png",
    label: "Gold throne room",
    tone: "gold",
    scope: "campaign",
    category: "interior",
    concept: "imperial audience chamber",
    keywords: ["throne", "citadel", "senate", "governor", "palace", "audience chamber"],
  },
  {
    id: "gold-palace-balcony",
    src: "/scene-art/gold_palace_balcony.png",
    sourcePath: "assets/gold_palace_balcony.png",
    label: "Palace balcony",
    tone: "gold",
    scope: "campaign",
    category: "exterior",
    concept: "imperial balcony",
    keywords: ["balcony", "villa", "estate", "garden", "terrace", "atrium"],
  },
  {
    id: "royal-landing-pad",
    src: "/scene-art/royal_landing_pad.png",
    sourcePath: "assets/royal_landing_pad.png",
    label: "Royal landing pad",
    tone: "gold",
    scope: "campaign",
    category: "transit",
    concept: "imperial shuttle landing zone",
    keywords: ["landing", "pad", "shuttle", "arrival", "hangar", "platform"],
  },
  {
    id: "light-bringer",
    src: "/scene-art/light_bringer.png",
    sourcePath: "assets/light_bringer.png",
    label: "Starship exterior",
    tone: "gold",
    scope: "generic",
    category: "space",
    concept: "torchship exterior",
    keywords: ["dreadnought", "torchship", "warship", "flagship", "ship exterior"],
  },
  {
    id: "space-docks",
    src: "/scene-art/space_docks.png",
    sourcePath: "assets/space_docks.png",
    label: "Orbital docks",
    tone: "friendly",
    scope: "generic",
    category: "industrial",
    concept: "orbital shipyard",
    keywords: ["dock", "docks", "port", "shipyard", "orbital", "hangar", "drydock"],
  },
  {
    id: "mars-docks",
    src: "/scene-art/mars_docks.png",
    sourcePath: "assets/mars_docks.png",
    label: "Industrial docks",
    tone: "friendly",
    scope: "generic",
    category: "industrial",
    concept: "freight loading dock",
    keywords: ["freight", "cargo", "loading", "warehouse", "dock", "bay"],
  },
  {
    id: "ship-halls",
    src: "/scene-art/ship_halls.png",
    sourcePath: "assets/ship_halls.png",
    label: "Ship interior",
    tone: "friendly",
    scope: "generic",
    category: "interior",
    concept: "starship corridor",
    keywords: ["hall", "corridor", "interior", "bulkhead", "passage", "ship hall"],
  },
  {
    id: "tram",
    src: "/scene-art/tram.png",
    sourcePath: "assets/tram.png",
    label: "Tram line",
    tone: "friendly",
    scope: "generic",
    category: "transit",
    concept: "urban tram platform",
    keywords: ["tram", "rail", "transit", "spine", "platform", "train"],
  },
  {
    id: "red-bar",
    src: "/scene-art/red_bar.png",
    sourcePath: "assets/red_bar.png",
    label: "Low-district bar",
    tone: "friendly",
    scope: "generic",
    category: "social",
    concept: "worker bar",
    keywords: ["bar", "cantina", "taproom", "club", "drinking hole"],
  },
  {
    id: "factory",
    src: "/scene-art/factory.png",
    sourcePath: "assets/factory.png",
    label: "Factory district",
    tone: "friendly",
    scope: "generic",
    category: "industrial",
    concept: "industrial plant",
    keywords: ["factory", "plant", "forge", "refinery", "works", "assembly"],
  },
  {
    id: "mars-district",
    src: "/scene-art/mars_district.png",
    sourcePath: "assets/mars_district.png",
    label: "Dense district",
    tone: "friendly",
    scope: "generic",
    category: "urban",
    concept: "dense low-color district",
    keywords: ["district", "block", "market", "street", "row"],
  },
  {
    id: "luna-low-district",
    src: "/scene-art/luna_low_district.png",
    sourcePath: "assets/luna_low_district.png",
    label: "Low district",
    tone: "friendly",
    scope: "generic",
    category: "urban",
    concept: "undercity tenement district",
    keywords: ["low district", "undercity", "tenement", "slum", "lower levels"],
  },
  {
    id: "red-miner",
    src: "/scene-art/red_miner.png",
    sourcePath: "assets/red_miner.png",
    label: "Worker quarter",
    tone: "friendly",
    scope: "generic",
    category: "labor",
    concept: "red worker habitat",
    keywords: ["mine", "miner", "pit", "worker", "barracks", "hab block"],
  },
];

export function normalizeSceneText(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function resolveSceneArt({ currentLocation, objective, sceneTone, selectedCampaign }) {
  const searchText = normalizeSceneText(
    [currentLocation, objective, selectedCampaign?.name, selectedCampaign?.tagline]
      .filter(Boolean)
      .join(" "),
  );

  const exactMatch = SCENE_ART_LIBRARY.find((entry) =>
    entry.keywords.some((keyword) => searchText.includes(normalizeSceneText(keyword))),
  );
  if (exactMatch) {
    return exactMatch;
  }

  return SCENE_ART_LIBRARY.find((entry) => entry.tone === sceneTone) ?? SCENE_ART_LIBRARY[0];
}
